CREATE DATABASE biblioteca;

USE biblioteca;

CREATE TABLE autores(
id INT(10) NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
data_nascimento DATETIME NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE livros(
id INT(100) NOT NULL AUTO_INCREMENT,
titulo VARCHAR(100) NOT NULL,
ano_publicado INT(4) NOT NULL,
id_autor INT(10),
PRIMARY KEY(id),
FOREIGN KEY (id_autor) REFERENCES autores(id)
);

CREATE TABLE membros