CREATE DATABASE ClinicaVetBD;

USE ClinicaVetBD;

CREATE TABLE Veterinarios(
id INT(10) NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
especialidade VARCHAR(100) NOT NULL,
telefone VARCHAR(11) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE Clientes(
id INT(10) NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
endereco VARCHAR(100) NOT NULL,
telefone VARCHAR(11) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE Pets(
id INT(10) NOT NULL AUTO_INCREMENT,
idCliente INT(10) NOT NULL,
nome VARCHAR(100) NOT NULL,
tipo VARCHAR(100) NOT NULL,
raca VARCHAR(100) NOT NULL,
dataNascimento DATETIME NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idCliente) REFERENCES Clientes(id)
);

CREATE TABLE Atendimentos(
id INT(10) NOT NULL AUTO_INCREMENT,
idPet INT(10) NOT NULL,
idVeterinario INT(10) NOT NULL,
dataAtendimento DATETIME NOT NULL,
descricao VARCHAR(300) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idPet) REFERENCES Pets(id),
FOREIGN KEY (idVeterinario) REFERENCES Veterinarios(id)
);